module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?@?react-native(?!.*node_modules)|@react-native-community|@react-navigation|react-native-safe-area-context|react-native-paper|react-native-vector-icons)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverage: true,
  collectCoverageFrom: [
    'packages/paysafe-payments-sdk-common/src/**/*.{ts,tsx}',
    'packages/paysafe-venmo/src/**/*.{ts,tsx}',
    'packages/paysafe-google-pay/src/**/*.{ts,tsx}',
    'packages/paysafe-card-payments/src/**/*.{ts,tsx}',
    'packages/paysafe-apple-pay/src/**/*.{ts,tsx}',
    'DemoAppExpo/src/**/*.{ts,tsx}',
    'DemoAppExpo/components/**/*.{ts,tsx}',
    'DemoAppExpo/hooks/**/*.{ts,tsx}',
    'DemoAppExpo/constants/**/*.{ts,tsx}',
    'DemoAppExpo/App.tsx',
    'DemoAppExpo/app/**/*.{ts,tsx}',
    '!**/__tests__/**',
    '!**/__mocks__/**',
    '!**/*.test.{ts,tsx}',
    '!**/*.spec.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!**/coverage/**',
    '!DemoAppExpo/App.tsx',
    '!DemoAppExpo/components/Collapsible.tsx',
    '!DemoAppExpo/constants/Colors.ts',
    '!DemoAppExpo/hooks/useColorScheme.web.ts',
    '!**/app/_layout.tsx',
    '!**/app/**/_layout.tsx',
    '!**/+not-found.tsx',
    '!**/app/**/payments.tsx',
    '!**/components/HelloWave.tsx',
    '!**/components/ExternalLink.tsx',
    '!**/components/ParallaxScrollView.tsx',
    '!**/components/HapticTab.tsx',
    '!**/components/ui/IconSymbol*.tsx',
    '!**/components/ui/TabBarBackground*.tsx',
  ],
  coverageDirectory: '<rootDir>/tests-report/coverage',
  coverageReporters: ['text', 'text-summary', 'lcov', 'json', 'cobertura', 'html'],
  coverageThreshold: {
    global: {
      branches: 85,
      functions: 85,
      lines: 85,
      statements: 85
    }
  },
  testResultsProcessor: "jest-junit",
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '^react-native$': '<rootDir>/node_modules/react-native',
    '^react-native/(.*)$': '<rootDir>/node_modules/react-native/$1',
    '^@react-native/(.*)$': '<rootDir>/node_modules/@react-native/$1',
    '^paysafe-payments-sdk-common$': '<rootDir>/packages/paysafe-payments-sdk-common/src',
    '^paysafe-venmo$': '<rootDir>/packages/paysafe-venmo/src',
    '^paysafe-google-pay$': '<rootDir>/packages/paysafe-google-pay/src',
    '^paysafe-card-payments$': '<rootDir>/packages/paysafe-card-payments/src',
    '^paysafe-apple-pay$': '<rootDir>/packages/paysafe-apple-pay/src',
    '^@/(.*)$': '<rootDir>/DemoAppExpo/$1',
    '^@components/(.*)$': '<rootDir>/DemoAppExpo/components/$1',
    '^@hooks/(.*)$': '<rootDir>/DemoAppExpo/hooks/$1',
    '^@constants/(.*)$': '<rootDir>/DemoAppExpo/constants/$1',
  },
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', {
      tsconfig: {
        jsx: 'react-jsx',
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        skipLibCheck: true,
        allowJs: true,
      },
    }],
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  testMatch: [
    '<rootDir>/packages/**/__tests__/**/*.{ts,tsx}',
    '<rootDir>/packages/**/?(*.)+(spec|test).{ts,tsx}',
    '<rootDir>/DemoAppExpo/**/__tests__/**/*.{ts,tsx}',
    '<rootDir>/DemoAppExpo/**/?(*.)+(spec|test).{ts,tsx}'
  ],
  clearMocks: true,
  maxWorkers: '50%',
  modulePathIgnorePatterns: ["<rootDir>/dist/"]
};
